/* Bundle entry for the Claude Design import. GENERATED by gen-entry.mjs -
 * regenerate with `node .design-sync/gen-entry.mjs`, then run prettier on the
 * result; cfg.buildCmd does both. Do not hand-edit.
 *
 * Why this file exists: this repo is a Next.js app with no library dist, so
 * the converter would otherwise synthesize an entry re-exporting EVERY .tsx
 * under src/ - dragging in server components, Leaflet and three.js. Naming the
 * exact surface here keeps the bundle to the synced scope.
 *
 * Every PascalCase export below lands on window.Gnars. Compound parts
 * (CardHeader, DialogFooter, ...) ship without their own preview card so the
 * design agent can still compose with them. */

import * as React from "react";
import { NextIntlClientProvider } from "next-intl";
import about from "../messages/en/about.json";
import auctions from "../messages/en/auctions.json";
import base from "../messages/en/base.json";
import blogs from "../messages/en/blogs.json";
import bounties from "../messages/en/bounties.json";
import coinProposal from "../messages/en/coinProposal.json";
import common from "../messages/en/common.json";
import createCoin from "../messages/en/createCoin.json";
import droposals from "../messages/en/droposals.json";
import errors from "../messages/en/errors.json";
import feed from "../messages/en/feed.json";
import footer from "../messages/en/footer.json";
import home from "../messages/en/home.json";
import installations from "../messages/en/installations.json";
import map from "../messages/en/map.json";
import members from "../messages/en/members.json";
import metadata from "../messages/en/metadata.json";
import migrate from "../messages/en/migrate.json";
import mural from "../messages/en/mural.json";
import nav from "../messages/en/nav.json";
import newhome from "../messages/en/newhome.json";
import propdates from "../messages/en/propdates.json";
import proposals from "../messages/en/proposals.json";
import propose from "../messages/en/propose.json";
import shop from "../messages/en/shop.json";
import stake from "../messages/en/stake.json";
import store from "../messages/en/store.json";
import swap from "../messages/en/swap.json";
import treasury from "../messages/en/treasury.json";
import tv from "../messages/en/tv.json";
import wallet from "../messages/en/wallet.json";

// shadcn/ui layer - the components this repo themes with the Gnars tokens.
export * from "@/components/ui/ConnectButton";
export * from "@/components/ui/accordion";
export * from "@/components/ui/address-display";
export * from "@/components/ui/alert-dialog";
export * from "@/components/ui/alert";
export * from "@/components/ui/aspect-ratio";
export * from "@/components/ui/avatar";
export * from "@/components/ui/badge";
export * from "@/components/ui/button-group";
export * from "@/components/ui/button";
export * from "@/components/ui/card";
export * from "@/components/ui/chart";
export * from "@/components/ui/checkbox";
export * from "@/components/ui/collapsible";
export * from "@/components/ui/command";
export * from "@/components/ui/count-up";
export * from "@/components/ui/dialog";
export * from "@/components/ui/drawer";
export * from "@/components/ui/dropdown-menu";
export * from "@/components/ui/field";
export * from "@/components/ui/input-group";
export * from "@/components/ui/input";
export * from "@/components/ui/label";
export * from "@/components/ui/navigation-menu";
export * from "@/components/ui/popover";
export * from "@/components/ui/progress";
export * from "@/components/ui/radio-group";
export * from "@/components/ui/scroll-area";
export * from "@/components/ui/select";
export * from "@/components/ui/separator";
export * from "@/components/ui/sheet";
export * from "@/components/ui/skeleton";
export * from "@/components/ui/slider";
export * from "@/components/ui/sonner";
export * from "@/components/ui/spinner";
export * from "@/components/ui/switch";
export * from "@/components/ui/table";
export * from "@/components/ui/tabs";
export * from "@/components/ui/textarea";
export * from "@/components/ui/token-image";
export * from "@/components/ui/tooltip";
export * from "@/components/ui/video-player";
export * from "@/components/ui/video-thumbnail-selector";

// Gnars feature components: prop-driven, no network or wallet dependency.
export * from "@/components/nogglesrails/RailCard";
export * from "@/components/nogglesrails/NounstacleDefinition";
export * from "@/components/nogglesrails/NogglesRailsManifesto";
export * from "@/components/nogglesrails/NogglesRailsClosingBox";
export * from "@/components/store/ProductCard";
export * from "@/components/store/StoreHero";
export * from "@/components/store/ProductVisual";
export * from "@/components/snapshot/SnapshotProposalCard";
export * from "@/components/auction/BidItem";
export * from "@/components/stake/TokenMark";
export * from "@/components/stake/SectionHeader";
export * from "@/components/stake/StakeFlowChart";
export * from "@/components/stake/RoadmapSection";
export * from "@/components/coin-proposal/CoinPurchasePreview";
export * from "@/components/home/AnimatedDescription";
export * from "@/components/propdates/PropdateDetail";

/* Every string in this DS goes through next-intl, so a component calling
 * useTranslations() throws outside a provider. Messages are imported from the
 * repo's own EN namespace files rather than copied into config, so they cannot
 * drift from what the site ships. */
export const dsMessages = {
  about: about,
  auctions: auctions,
  base: base,
  blogs: blogs,
  bounties: bounties,
  coinProposal: coinProposal,
  common: common,
  createCoin: createCoin,
  droposals: droposals,
  errors: errors,
  feed: feed,
  footer: footer,
  home: home,
  installations: installations,
  map: map,
  members: members,
  metadata: metadata,
  migrate: migrate,
  mural: mural,
  nav: nav,
  newhome: newhome,
  propdates: propdates,
  proposals: proposals,
  propose: propose,
  shop: shop,
  stake: stake,
  store: store,
  swap: swap,
  treasury: treasury,
  tv: tv,
  wallet: wallet,
};

export function GnarsProvider({ children }: { children?: React.ReactNode }) {
  return (
    <NextIntlClientProvider locale="en" messages={dsMessages as never}>
      {children}
    </NextIntlClientProvider>
  );
}
