import { readdirSync, writeFileSync } from "node:fs";

const EXCL = new Set(["map.tsx", "place-autocomplete.tsx"]);
const ui = readdirSync("src/components/ui")
  .filter((f) => f.endsWith(".tsx") && !EXCL.has(f))
  .sort();
const feat = [
  "nogglesrails/RailCard",
  "nogglesrails/NounstacleDefinition",
  "nogglesrails/NogglesRailsManifesto",
  "nogglesrails/NogglesRailsClosingBox",
  "store/ProductCard",
  "store/StoreHero",
  "store/ProductVisual",
  "snapshot/SnapshotProposalCard",
  "auction/BidItem",
  "stake/TokenMark",
  "stake/SectionHeader",
  "stake/StakeFlowChart",
  "stake/RoadmapSection",
  "coin-proposal/CoinPurchasePreview",
  "home/AnimatedDescription",
  "propdates/PropdateDetail",
];
const ns = readdirSync("messages/en")
  .filter((f) => f.endsWith(".json"))
  .map((f) => f.replace(/\.json$/, ""))
  .sort();
const ident = (s) => s.replace(/[^A-Za-z0-9]/g, "_");

const L = [];
L.push(`/* Bundle entry for the Claude Design import. GENERATED by gen-entry.mjs -`);
L.push(` * regenerate with \`node .design-sync/gen-entry.mjs\`, then run prettier on the`);
L.push(` * result; cfg.buildCmd does both. Do not hand-edit.`);
L.push(` *`);
L.push(` * Why this file exists: this repo is a Next.js app with no library dist, so`);
L.push(` * the converter would otherwise synthesize an entry re-exporting EVERY .tsx`);
L.push(` * under src/ - dragging in server components, Leaflet and three.js. Naming the`);
L.push(` * exact surface here keeps the bundle to the synced scope.`);
L.push(` *`);
L.push(` * Every PascalCase export below lands on window.Gnars. Compound parts`);
L.push(` * (CardHeader, DialogFooter, ...) ship without their own preview card so the`);
L.push(` * design agent can still compose with them. */`);
L.push("");
// Imports come first because the repo's prettier config hoists them; emitting
// them lower down makes `prettier --check` fail on every regeneration.
L.push('import * as React from "react";');
L.push('import { NextIntlClientProvider } from "next-intl";');
for (const n of ns) L.push(`import ${ident(n)} from "../messages/en/${n}.json";`);
L.push("");
L.push("// shadcn/ui layer - the components this repo themes with the Gnars tokens.");
for (const f of ui) L.push(`export * from "@/components/ui/${f.replace(/\.tsx$/, "")}";`);
L.push("");
L.push("// Gnars feature components: prop-driven, no network or wallet dependency.");
for (const p of feat) L.push(`export * from "@/components/${p}";`);
L.push("");
L.push("/* Every string in this DS goes through next-intl, so a component calling");
L.push(" * useTranslations() throws outside a provider. Messages are imported from the");
L.push(" * repo's own EN namespace files rather than copied into config, so they cannot");
L.push(" * drift from what the site ships. */");
// Quote a key only when it is not a bare identifier - prettier strips the
// quotes JSON.stringify would put on every one of them.
const key = (n) => (/^[A-Za-z_$][A-Za-z0-9_$]*$/.test(n) ? n : JSON.stringify(n));
L.push(`export const dsMessages = {\n${ns.map((n) => `  ${key(n)}: ${ident(n)},`).join("\n")}\n};`);
L.push("");
L.push("export function GnarsProvider({ children }: { children?: React.ReactNode }) {");
L.push("  return (");
L.push('    <NextIntlClientProvider locale="en" messages={dsMessages as never}>');
L.push("      {children}");
L.push("    </NextIntlClientProvider>");
L.push("  );");
L.push("}");
L.push("");

writeFileSync(".design-sync/ds-entry.tsx", L.join("\n"));
console.log("ui files:", ui.length, "| feature:", feat.length, "| namespaces:", ns.length);
